### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DataDrug** [AlessandroZ/LaZagneForensic#3]
Sorry to keep spamming your mail with this issues, but I've found that the forensic version could be more helpfull to me. However, when runing it I get this error:

```
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
		
Traceback (most recent call last):
  File "laZagneForensic.py", line 380, in <module>
    for r in runLaZagne(category_choosed=category_choosed, password=constant.user_password, pwdhash=constant.user_pwdhash):
  File "laZagneForensic.py", line 259, in runLaZagne
    constant.user_dpapi = Decrypt_DPAPI(password=password, pwdhash=pwdhash)
  File "/root/Desktop/LaZagneForensic/LaZagneForensic/lazagne/config/dpapi.py", line 40, in __init__
    masterkeydir 	= os.path.join(protect_folder, self.sid)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Do i need some extra operation before running it ?

Thanks

**Comment by AlessandroZ** [comment]
Should be fixed now. Thanks for reporting !

**Comment by DataDrug** [comment]
Sorry for just giving feedback now.

The big problem was that I was trying to recover some credentials from a AppData sub folder, that belonged to an account that was bound to a Active Directory group.
Without being on the AD it was impossible for me to "crack" the password.
