### ISSUE TITLE
problem with laZagneFORensic

### ISSUE THREAD

**Issue by JhonShell** [AlessandroZ/LaZagneForensic#4]
PS C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic> python laZagneForensic.py all -remote /tmp/dump
Traceback (most recent call last):
  File "laZagneForensic.py", line 16, in <module>
    from lazagne.config.dpapi import Decrypt_DPAPI
  File "C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic\lazagne\config\dpapi.py", line 4, in <module
    from lazagne.config.DPAPI.masterkey import *
  File "C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic\lazagne\config\DPAPI\masterkey.py", line 11,
dule>
    from structures import *
  File "C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic\lazagne\config\DPAPI\structures.py", line 12
module>
    'data'              / String(this.length, encoding='UTF_16_LE'),
NameError: name 'String' is not defined
PS C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic>

PS C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic> python laZagneForensic.py all -remote /tmp/dump -pass
word 'mypassoword'
Traceback (most recent call last):
  File "laZagneForensic.py", line 16, in <module>
    from lazagne.config.dpapi import Decrypt_DPAPI
  File "C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic\lazagne\config\dpapi.py", line 4, in <module>
    from lazagne.config.DPAPI.masterkey import *
  File "C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic\lazagne\config\DPAPI\masterkey.py", line 11, in <
module>
    from structures import *
  File "C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic\lazagne\config\DPAPI\structures.py", line 124, in
 <module>
    'data'              / String(this.length, encoding='UTF_16_LE'),
NameError: name 'String' is not defined
PS C:\Users\prueba\Desktop\LaZagneForensic-master\LaZagneForensic

#################################################
I not understand because not work, i really all dependency .
######################################################
###################################
regards.
###########################

**Comment by AlessandroZ** [comment]
Should be fixed now, the construct lib changes its syntax every two weeks. I changed the requirements file as well to avoid having this problem again. 
Thanks !!
