### ISSUE TITLE
Problem installing LaZagne on Raspberry pi 3 

### ISSUE THREAD

**Issue by adalbertobrant** [AlessandroZ/LaZagneForensic#6]
Hi I have an issue trying to install LaZagne

**Comment by adalbertobrant** [comment]
Traceback (most recent call last):
  File "laZagneForensic.py", line 16, in <module>
    from lazagne.config.dpapi import Decrypt_DPAPI
  File "/home/pi/lazagne/LaZagneForensic/LaZagneForensic/lazagne/config/dpapi.py", line 4, in <module>
    from lazagne.config.DPAPI.masterkey import *
  File "/home/pi/lazagne/LaZagneForensic/LaZagneForensic/lazagne/config/DPAPI/masterkey.py", line 11, in <module                        >
    from structures import *
  File "/home/pi/lazagne/LaZagneForensic/LaZagneForensic/lazagne/config/DPAPI/structures.py", line 14, in <modul                        e>
    import pytz
ImportError: No module named pytz
